### ISSUE TITLE
Remove the .tex extension from the include command

### ISSUE THREAD

**Issue by juananpe** [gvwilson/sdxjs#1]
I think that this line:
https://github.com/gvwilson/sdxjs/blob/657a10c6b292710bc588effe813f18c3b8b051a1/info/head.tex#L184
should just be `\include{config}`. At least that did the trick in my case - pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019) - , allowing me to generate a proper PDF with `make pdf-once` without errors.
See also: https://tex.stackexchange.com/a/34793

**Comment by gvwilson** [comment]
Thank you for catching that - just pushed the fix.
