### ISSUE TITLE
ModuleNotFoundError: No module named 'pymdownx' when launching ivy

### ISSUE THREAD

**Issue by juananpe** [gvwilson/sdxjs#3]
I think that `pymdown-extensions` should be added as another requirement here:
https://github.com/gvwilson/sdxjs/blob/main/requirements.txt
Otherwise we will get a "ModuleNotFoundError: No module named 'pymdownx'" error when launching ivy via the `make serve` command. Not sure which version should be added, though. I tried with the latest one and it worked
(_pymdown-extensions>=9.5_)

**Comment by gvwilson** [comment]
thank you for spotting that
