### ISSUE TITLE
Exercises solutions

### ISSUE THREAD

**Issue by adecora** [gvwilson/sdxjs#53]
Is there any repo or page that we can check to validate the solutions to the exercises at the end of each section?

**Comment by gvwilson** [comment]
Hi @adecora - no, I deliberately haven't done that so that course instructors can use the exercises without worrying about plagiarism. cheers - @gvwilson

**Comment by adecora** [comment]
Okey!!! I'm solving it by my own, but it's always nice to have a check for doubts. Thanks a lot for the such a nice material @gvwilson !!!!!
